### ISSUE TITLE
技術的な課題調査

### ISSUE THREAD

**Issue by shunsuke227ono** [shunsuke227ono/alpha_homerun_battle#1]
- [ ] ひとまず簡単なgame作ってみる。
- [ ] 類似ゲーム探す。(むしろ類似ゲームが存在するものを作る？)

**Comment by shunsuke227ono** [comment]
@yojimasentaro 調べていい感じのあったらここに共有お願いします〜。

**Comment by shunsuke227ono** [comment]
@Kozy1625 ここで議論します

**Comment by yojimasentaro** [comment]
当たり判定
http://wise9.jp/archives/1992
